name: duckdb
version: "1.0"
config-version: 2

profile: duckdb

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
  duckdb:
    bronze:
      +schema: bronze
    silver:
      +schema: silver
    gold:
      +schema: gold
