duckdb:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /home/airflow/duckdb/dbt.duckdb
      extensions:
        - httpfs
        - parquet
        - s3
      settings:
        s3_region: us-east-1
        s3_endpoint: minio:9000
        s3_access_key_id: minio
        s3_secret_access_key: minio123
        s3_url_style: path
        s3_use_ssl: false
