version: "3.8"

services:

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        until mc alias set local http://minio:9000 minio minio123; do sleep 1; done;
        mc alias set local http://minio:9000 minio minio123 &&
        mc mb --ignore-existing local/raw &&        
        mc mb --ignore-existing local/bronze &&
        mc mb --ignore-existing local/silver &&
        mc mb --ignore-existing local/gold &&
        mc mkdir --ignore-existing local/bronze/breweries_bronze &&
        mc mkdir --ignore-existing local/silver/breweries_silver &&
        mc mkdir --ignore-existing local/gold/breweries_gold
      "

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-webserver:
    build:
      context: .
      dockerfile: ./airflow/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "minha_chave_supersegura_1234567890123456"
      AIRFLOW__CORE__FERNET_KEY: "9x1Wz5ubTtRkGlGSMNVWta8aTbP5jmnpJm2dJrJcOC4="
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/scripts:/opt/airflow/scripts
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dbt:/opt/dbt
      - .dbt/duckdb:/home/airflow/duckdb     
    command: >
      bash -c "
        airflow db migrate &&
        airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.org --password admin &&
        airflow webserver"

  airflow-scheduler:
    build:
      context: .
      dockerfile: ./airflow/Dockerfile
    depends_on:
      - postgres
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "minha_chave_supersegura_1234567890123456"
      AIRFLOW__CORE__FERNET_KEY: "9x1Wz5ubTtRkGlGSMNVWta8aTbP5jmnpJm2dJrJcOC4="
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/scripts:/opt/airflow/scripts
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dbt:/opt/dbt
      - .dbt/duckdb:/home/airflow/duckdb     
    command: >
      bash -c "
        while ! airflow db check; do
          echo '⏳ Aguardando DB pronto...';
          sleep 3;
        done;
        echo '✅ Banco pronto. Iniciando scheduler...';
        airflow scheduler"


volumes:
  postgres_data:
